rapt: fix apt update

diff --git a/usr/bin/rapt b/usr/bin/rapt
--- a/usr/bin/rapt
+++ b/usr/bin/rapt
@@ -180,22 +180,68 @@ if [[ ! "" = "$@" ]] ; then
    unset arg
 fi
 
-## We don't want to preserve the environment to prevent any LD_PRELOAD tricks.
-output="$(env -i /usr/bin/apt-get --simulate --quiet=2 $command "${@}")"
+error_output() {
+   if [ ! "$output_stdout" = "" ] ; then
+      echo "$output_stdout"
+   fi
+   if [ ! "$output_stderr" = "" ] ; then
+      echo "$output_stderr"
+   fi
+}
 
-while read -r -d $'\n' line ; do
-   echo "line: $line"
-   read -r first second third <<< "$line" || true
-   if [ "$first" = "Remv" ]; then
+check_for_packages_on_refused_removal_list() {
+   ## output of includes (excerpt):
+   #sudo apt-get --simulate --quiet=2 purge apparmor
+   ##
+   ##Purg apparmor-profiles-hardened-debian [3:12.4-1]
+   ##Purg apparmor-profile-torbrowser [3:6.5-1]
+   ##Purg apparmor-utils [2.13.2-10]
+
+   ## Output of 'sudo apt-get --simulate --quiet=2 purge apparmor' does not
+   ## contain 'apparmor'. Therefore we have to iterate through the list of args.
+
+   for arg in "$@" ; do
       for package in $packages_refuse_removal ; do
-         if [ "$second" = "$package" ]; then
+         if [ "$arg" = "$package" ]; then
+            error_output
             echo "ERROR: forbidden to remove package! $package"
-            echo "output:"
-            echo "$output"
             exit 1
          fi
       done
+   done
+
+   while read -r -d $'\n' line ; do
+      read -r first second third <<< "$line" || true
+      if [ "$first" = "Remv" ]; then
+         for package in $packages_refuse_removal ; do
+            if [ "$second" = "$package" ]; then
+               error_output
+               echo "ERROR: forbidden to remove package! $package"
+               exit 1
+            fi
+         done
+      fi
+   done <<< "$output_stdout"
+}
+
+apt_simulate_exit_code=0
+## We don't want to preserve the environment to prevent any LD_PRELOAD tricks.
+output_stdout="$(env -i /usr/bin/apt-get --simulate --quiet=2 $command "${@}" 2>/dev/null)" || { apt_simulate_exit_code=$? ; true; }
+
+## How to safely capture stdout and stderr into different variables in a single command?
+output_stderr="$(env -i /usr/bin/apt-get --simulate --quiet=2 $command "${@}" 2>&1 1>/dev/null)" || { apt_simulate_exit_code=$? ; true; }
+
+if [ "$apt_simulate_exit_code" = "100" ]; then
+   if [ "$output_stderr" = "E: Command line option --simulate is not understood in combination with the other options" ]; then
+      ## Could be a simple 'apt-get update'.
+      true "apt output_stderr has expected value. Permitting."
+   else
+      echo "$output_stdout"
+      echo "$output_stderr"
+      exit "$apt_simulate_exit_code"
    fi
-done <<< "$output"
+fi
+
+check_for_packages_on_refused_removal_list "$@"
 
 env -i /usr/bin/apt-get $command "${@}"
